using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Serilog;

namespace Swiss.FCh.Utils.Rhos.Extensions;

/// <summary>
/// This class offers extension methods that are used to ease the integration into the Redhat Openshift environment of the FOITT.
/// </summary>
public static class ConfigurationExtensions
{
    /// <summary>
    /// Recognizes the "STAGE" environment variable.
    /// If the environemnt is on RHOS, the configuration is read from the environment variables.
    /// Locally, the appsettings.development.json file is used.
    /// </summary>
    /// <param name="builder">The <see cref="Microsoft.Extensions.Hosting.IHostApplicationBuilder"/></param>
    /// <param name="stageEnvVarName">
    /// The name of the environment variable holding the information about the RHOS stage.
    /// Its default value is "STAGE".
    /// </param>
    /// <returns></returns>
    public static IHostApplicationBuilder AddRhosConfigurations(this IHostApplicationBuilder builder, string stageEnvVarName = "STAGE")
    {
        ArgumentNullException.ThrowIfNull(builder);

        var stage = Environment.GetEnvironmentVariable(stageEnvVarName);

        if (Stage.IsRhosStage(stage))
        {
            Log.Information("RHOS stage={Stage} detected, adding environment variables to configuration", stage);

            // Configuration that is not secret will come from the config map in the kubernetes deployment
            // and will be provided as environment variables matching the appsettings.json
            builder.Configuration.AddEnvironmentVariables();
        }

        return builder;
    }

    /// <summary>
    /// Adds the configuration for a PGSQL database on RHOS.
    /// </summary>
    /// <param name="builder">The <see cref="Microsoft.Extensions.Hosting.IHostApplicationBuilder"/></param>
    /// <param name="stageEnvVarName">
    /// The name of the environment variable holding the information about the RHOS stage.
    /// Its default value is "STAGE".
    /// </param>
    /// <param name="vaultPath">
    /// Path to the credentials file generated by the vault.
    /// Its default value is: ../vault/secrets/pg-database-credentials.json
    /// </param>
    /// <returns></returns>
    public static IHostApplicationBuilder AddRhosPostgresConfiguration(
        this IHostApplicationBuilder builder,
        string stageEnvVarName = "STAGE",
        string vaultPath = "../vault/secrets/pg-database-credentials.json")
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(vaultPath);

        AddRhosJsonConfiguration(builder, vaultPath, stageEnvVarName);

        return builder;
    }

    /// <summary>
    /// Adds the configuration for as S3 object store on RHOS.
    /// </summary>
    /// <param name="builder">The <see cref="Microsoft.Extensions.Hosting.IHostApplicationBuilder"/></param>
    /// <param name="stageEnvVarName">
    /// The name of the environment variable holding the information about the RHOS stage.
    /// Its default value is "STAGE".
    /// </param>
    /// <param name="vaultPath">
    /// Path to the credentials file generated by the vault.
    /// Its default value is: ../vault/secrets/s3-credentials.json
    /// </param>
    /// <returns></returns>
    public static IHostApplicationBuilder AddRhosS3Configuration(
        this IHostApplicationBuilder builder,
        string stageEnvVarName = "STAGE",
        string vaultPath = "../vault/secrets/s3-credentials.json")
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(vaultPath);

        AddRhosJsonConfiguration(builder, vaultPath, stageEnvVarName);

        return builder;
    }

    /// <summary>
    /// Get the postgres connection string from the configuration.
    /// Make sure to call <see cref="AddRhosPostgresConfiguration"/> first.
    /// </summary>
    /// <param name="configuration">The <see cref="Microsoft.Extensions.Configuration.IConfiguration"/> to read from.</param>
    /// <returns>The connection string to the PGSQL database read from the respective configuration.</returns>
    public static string GetPostgresConnectionString(this IConfiguration configuration)
    {
        var host = configuration.GetValue<string>("pgsql:hostname");
        var port = configuration.GetValue<string>("pgsql:port");
        var user = configuration.GetValue<string>("pgsql:username");
        var pass = configuration.GetValue<string>("pgsql:password");
        var database = configuration.GetValue<string>("pgsql:database_name");
        var connectionString = $"Host={host};Port={port};Username={user};Password={pass};Database={database};";
        return connectionString;
    }

    private static void AddRhosJsonConfiguration(IHostApplicationBuilder builder, string vaultPath, string stageEnvVarName = "STAGE")
    {
        var stage = Environment.GetEnvironmentVariable(stageEnvVarName);
        if (Stage.IsRhosStage(stage))
        {
            Log.Information("RHOS stage={Stage} detected, adding json file {JSONFile}", stage, vaultPath);

            if (vaultPath.StartsWith("..", StringComparison.InvariantCultureIgnoreCase)) //secrets files are outside of the applications scope
            {
                // These files are placed in the pod by the vault agent, and they match the secrets of our appsettings.json file
                // ConfigurationBuilder.AddJsonFile will NOT load files that are above the root directory, hence the stream reading...
                var stream = File.OpenRead(vaultPath);

                builder.Configuration.AddJsonStream(stream);

                stream.Dispose();
            }
            else
            {
                builder.Configuration.AddJsonFile(vaultPath); //files inside the applications scope can be loaded "normally"
            }
        }
    }
}
